### ISSUE TITLE
'App isn't installed' dialog while using widget

### ISSUE THREAD

**Issue by swachud** [BLumia/pineapple-lock-screen#6] opened 2023-06-06 12:17 UTC
I'm using android 13 on moto edge 30, which was a recent update from 12. After that, the widget doesn't seem to work after a restart, and recurringly after a certain time period.
![Screenshot_20230606-175513](https://github.com/BLumia/pineapple-lock-screen/assets/52316922/98f99414-5026-4003-8728-cf9733ef1e70)

Only workaround is removing the old widget and adding it again. Since the app doesn't show up in drawer, I guess something is preventing it from working correctly. When I open the app from Settings>Apps it works there, but not from the widget.

**Comment by swachud** [comment] 2023-06-07 02:39
I will try that, but the aesthetic aspect of it was what I actually required. Also off-topic, but it would be great if you could add a quick settings tile too for locking screen. That seems like a better alternative but also a good add into the functionality of this app. And making the icon compatible with themed icon of android 13 would also be helpful.

**Comment by BLumia** [comment] 2023-06-07 06:59
> but the aesthetic aspect of it was what I actually required.

Yeah I understand, I also want to have an icon that can be used to turn off the screen and without a corner badge icon. I'm just not sure if it's still possible to achieve that in Android 13, since the original method I use was already an undocumented and deprecated API.

I am also consider if we can introduce a new method to lock the screen. When a11y service permission is granted, just click the application icon to lock the screen. Thus user won't even need to create a shortcut from the widget screen from the first place.

> Also off-topic, but it would be great if you could add a quick settings tile too for locking screen.

This application actually already have such feature, but it's not available in the free version in the Play Store. To get the version that include the Quick Setting tile, you can either:

1. Get the Plus version from Play Store (will cost 1 dollar).
2. Get the OSS version from F-droid (free, feature set identical with the Plus version but logo color is different).
3. Build the application from source if you like :D

HTH :)

**Comment by BLumia** [comment] 2023-10-04 03:07
>> but the aesthetic aspect of it was what I actually required.
>
> I am also consider if we can introduce a new method to lock the screen. When a11y service permission is granted, just click the application icon to lock the screen. Thus user won't even need to create a shortcut from the widget screen at the first place.

I finally got some free time to implement this. I added an option to allow user click the app icon itself to lock the screen and you can try this feature by downloading the following attachment and install/sideload it:

[app-free-release.zip](https://github.com/BLumia/pineapple-lock-screen/files/12798846/app-free-release.zip)

I haven't bumped the version yet so the system might say it's not an update. Also, the APK is signed by myself using my own key so the signer will be different if you previously get the application via F-droid instead of Google Play. 

Feel free to let me know if that's working and if you have any suggestions/feedback :)

**Comment by nsty** [comment] 2023-10-12 21:51
Thanks for the patch but it's not working for me. The system said it's an update but during installation there was an error, probably because of the different signature. So I had to remove the other version and reinstall.

With the update, the widget is not working any more at all. Before the update, it was working several times and after some time stopped working.

I'm not able to turn on the accessibility settings. This wasn't working before the update either, still the widget was working for a few times. Any idea if this might be the root cause?

![Screenshot_20231012-233930~2](https://github.com/BLumia/pineapple-lock-screen/assets/2273779/b7a97cc6-c9c7-4342-a0c4-6cffc268e7c1)

**Comment by BLumia** [comment] 2023-10-13 03:18
For the "Restricted setting" issue, please refer to this comment: https://github.com/BLumia/pineapple-lock-screen/issues/4#issuecomment-1384926557 @nsty

**Comment by nsty** [comment] 2023-10-13 23:23
Oh thank you. Actually I was just about to post an update. I reinstalled the older version from F-droid store and it wasn't working anymore. I'm even wondering how it was working earlier without the accessibility settings being enabled. I'm gonna let you know if the widget is now working.

**Comment by nsty** [comment] 2023-10-14 14:42
It is working now with the "Use application icon to lock" option. Thank you.

For the widget, it reproducibly crashes always after a device reboot. But I'm happy with the other method.

**Comment by BLumia** [comment] 2023-10-15 07:56
Thanks! I'll close this issue once I made a tag release (usually when the Google Play version is also ready) :)

**Comment by BLumia** [comment] 2023-10-17 11:45
The Google Play version is now live (1.3.0 is the version that contains the new feature). Feel free to try it out :)

**Closed by BLumia** 2023-10-17 11:45 UTC
